name: Backup to remote

on:
  push:
    branches:
      - main # Replace with the main branch of your repository
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (UTC)

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches
          token: ${{ secrets.ZERO }}

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Add backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.back_rem }}@github.com/7eromy/backup-repo.git
          git remote -v
          
      - name: Push to backup repository
        run: |
          echo "Pushing to remote repository"
          git push backup main --force
