name: Backup to remote

on:
  push:
    branches:
      - main # Замените на главную ветку вашего репозитория
  schedule:
    - cron: '0 0 * * *' # Ежедневно в полночь (UTC)

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получить все ветки

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Add backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.repo-all-acc }}@github.com/7eromy/backup-repo.git
          git remote -v
          
      - name: Push to backup repository
        run: |
          echo "Pushing to remote repository"
          git push backup main --force
