name: Backup to remote

on:
  push:
    branches:
      - main # Замените на главную ветку вашего репозитория
  schedule:
    - cron: '0 21 * * *' # Ежедневно в полночь (UTC)

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получить все ветки

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Add backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.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 }}@github.com/7eromy/backup-repo.git
          git remote -v
          
      - name: Create backup branch name
        id: date
        run: |
          echo "Creating backup branch name"
          BACKUP_BRANCH="backup-$(date +'%Y-%m-%d')"
          echo "Backup branch name: $BACKUP_BRANCH"
          echo "::set-output name=backup_branch::$BACKUP_BRANCH"
          
      - name: Create and push to backup branch
        run: |
          echo "Creating and pushing to backup branch"
          git checkout -b ${{ steps.date.outputs.backup_branch }}
          git push backup ${{ steps.date.outputs.backup_branch }} --force
