name: Sync Repository

on:
  push:
    branches:
      - main # Replace with the main branch of your repository
  schedule:
    - cron: '0 0 * * *' # Daily at midnight (UTC)

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches
          token: ${{ secrets.ZERO }}

      - name: Set up Git
        run: |
          echo "Setting up Git configuration"
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Add backup remote
        run: |
          echo "Adding remote backup repository"
          git remote add backup https://${{ secrets.ZERO }}@github.com/TheZeromy/backup-repo.git
          git remote -v
          
      - name: Create backup branch name
        id: date
        run: |
          echo "Creating backup branch name"
          BACKUP_BRANCH="backup-$(date +'%Y-%m-%d')"
          echo "Backup branch name: $BACKUP_BRANCH"
          echo "::set-output name=backup_branch::$BACKUP_BRANCH"
          
      - name: Create and push to backup branch
        run: |
          echo "Creating and pushing to backup branch"
          git checkout -b ${{ steps.date.outputs.backup_branch }}
          git push backup ${{ steps.date.outputs.backup_branch }} --force
